Repository semeietech/website, pull requests merged in 2018-03, with the labels that each got.

#1 boileirpleate criado
  index.html
Labels: awaiting review

#7 botao principal
  css/botao.css
  html/botao.html
Labels: Done, awaiting review

#5 criei o missão
  css/missao.css
  img/missao_img.jpg
  index.html
  missao.html
Labels: In progress, awaiting review

#3 Task/cards
  css/style.css
  index.html
Labels: Done, merged
